[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["../../node_modules"]
solc = "../../.tooling/solc"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
remappings = ["@openzeppelin/contracts/=../../node_modules/@openzeppelin/contracts/", "forge-std/=../../node_modules/forge-std/src/"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = true

[profile.ci.fuzz]
runs = 2048

[profile.ci.invariant]
runs = 256
depth = 128
fail_on_revert = true

[fmt]
line_length = 110
tab_width = 4
bracket_spacing = true
